import React from 'react';
import { Head } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Printer } from 'lucide-react';
import { useTranslation } from 'react-i18next';

interface Section {
  id: number;
  name: string;
  code: string;
}

interface Props {
  sections: Section[];
  company_name: string;
  print_date: string;
}

export default function SectionReport({ sections, company_name, print_date }: Props) {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-white p-4 font-sans text-black">
      <Head title={t('Section Master Report')} />
      
      {/* Action Bar - Hidden during print */}
      <div className="fixed top-4 right-4 print:hidden">
        <Button onClick={() => window.print()} variant="default" className="bg-gray-800 text-white shadow-lg">
          <Printer className="w-4 h-4 mr-2" />
          {t('Print Report')}
        </Button>
      </div>

      <div className="max-w-[1000px] mx-auto border border-black p-8">
        {/* Header */}
        <div className="text-center border-b border-black pb-4 mb-6">
          <h1 className="text-xl font-bold uppercase mb-4">{company_name}</h1>
          <div className="flex justify-between items-end border-t border-black pt-4">
            <div className="text-sm">
              <span>Print Date: {print_date}</span>
            </div>
            <div className="text-2xl font-bold underline uppercase">
              Section Master
            </div>
            <div className="w-32 text-right text-xs">
               Page 1 of 1
            </div>
          </div>
        </div>

        {/* Table */}
        <table className="w-full border-collapse border border-black text-sm">
          <thead>
            <tr className="bg-gray-100 border-b border-black text-left">
              <th className="border-r border-black p-2 w-12 text-center">#</th>
              <th className="border-r border-black p-2 w-32">{t('Type of Code')}</th>
              <th className="border-r border-black p-2 w-48">{t('Short Code')}</th>
              <th className="p-2">{t('Full Name')}</th>
            </tr>
          </thead>
          <tbody>
            {sections.map((section, index) => (
              <tr key={section.id} className="border-b border-black">
                <td className="border-r border-black p-2 text-center">{index + 1}</td>
                <td className="border-r border-black p-2">SEC</td>
                <td className="border-r border-black p-2 font-medium">{section.code || '-'}</td>
                <td className="p-2 uppercase">{section.name}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Footer */}
        <div className="mt-12 flex justify-between px-4">
           <div className="text-xs italic">
             Generated by KIRAN ERP
           </div>
           <div className="text-center border-t border-black pt-2 min-w-[200px]">
             <span className="text-sm font-bold">Authorized Signatory</span>
           </div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body { padding: 0; }
          .max-w-[1000px] { border: none !important; width: 100% !important; max-width: 100% !important; padding: 0 !important; }
          @page { margin: 1.5cm; }
        }
        table { border-spacing: 0; }
      ` }} />
    </div>
  );
}
